src/Entity/Station.php
<?php

namespace App\Entity;

use App\Repository\StationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StationRepository::class)
 */
class Station
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $lon;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $station_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $current_dockCount;

    /**
     * @ORM\OneToMany(targetEntity=Bike::class, mappedBy="station")
     */
    private $bikes;

    /**
     * @ORM\OneToMany(targetEntity=Trip::class, mappedBy="from_station_id")
     */
    private $trips_from_station;

    /**
     * @ORM\OneToMany(targetEntity=Trip::class, mappedBy="to_station_id")
     */
    private $trips_to_station;

    public function __construct()
    {
        $this->bikes = new ArrayCollection();
        $this->trips_from_station = new ArrayCollection();
        $this->trips_to_station = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLon(): ?float
    {
        return $this->lon;
    }

    public function setLon(?float $lon): self
    {
        $this->lon = $lon;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(?float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getStationId(): ?string
    {
        return $this->station_id;
    }

    public function setStationId(?string $station_id): self
    {
        $this->station_id = $station_id;

        return $this;
    }

    public function getCurrentDockCount(): ?int
    {
        return $this->current_dockCount;
    }

    public function setCurrentDockCount(?int $current_dockCount): self
    {
        $this->current_dockCount = $current_dockCount;

        return $this;
    }

    /**
     * @return Collection|Bike[]
     */
    public function getBikes(): Collection
    {
        return $this->bikes;
    }

    public function addBike(Bike $bike): self
    {
        if (!$this->bikes->contains($bike)) {
            $this->bikes[] = $bike;
            $bike->setStation($this);
        }

        return $this;
    }

    public function removeBike(Bike $bike): self
    {
        if ($this->bikes->removeElement($bike)) {
            // set the owning side to null (unless already changed)
            if ($bike->getStation() === $this) {
                $bike->setStation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Trip[]
     */
    public function getTripsFromStation(): Collection
    {
        return $this->trips_from_station;
    }

    public function addTripsFromStation(Trip $tripsFromStation): self
    {
        if (!$this->trips_from_station->contains($tripsFromStation)) {
            $this->trips_from_station[] = $tripsFromStation;
            $tripsFromStation->setFromStationId($this);
        }

        return $this;
    }

    public function removeTripsFromStation(Trip $tripsFromStation): self
    {
        if ($this->trips_from_station->removeElement($tripsFromStation)) {
            // set the owning side to null (unless already changed)
            if ($tripsFromStation->getFromStationId() === $this) {
                $tripsFromStation->setFromStationId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Trip[]
     */
    public function getTripsToStation(): Collection
    {
        return $this->trips_to_station;
    }

    public function addTripsToStation(Trip $tripsToStation): self
    {
        if (!$this->trips_to_station->contains($tripsToStation)) {
            $this->trips_to_station[] = $tripsToStation;
            $tripsToStation->setToStationId($this);
        }

        return $this;
    }

    public function removeTripsToStation(Trip $tripsToStation): self
    {
        if ($this->trips_to_station->removeElement($tripsToStation)) {
            // set the owning side to null (unless already changed)
            if ($tripsToStation->getToStationId() === $this) {
                $tripsToStation->setToStationId(null);
            }
        }

        return $this;
    }
}

src/Form/StationType.php
<?php

namespace App\Form;

use App\Entity\Station;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('lon')
            ->add('lat')
            ->add('station_id')
            ->add('current_dockCount')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Station::class,
        ]);
    }
}

src/Controller/StationController.php
<?php

namespace App\Controller;

use App\Entity\Station;
use App\Entity\Bike;
use App\Form\StationType;
use App\Repository\StationRepository;
use App\Repository\BikeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/station")
 */
class StationController extends AbstractController
{
    /**
     * @Route("/", name="station_index", methods={"GET"})
     */
    public function index(StationRepository $stationRepository): Response
    {
        return $this->json($stationRepository->findAllForJson());
    }

    /**
     * @Route("/{id}", name="station_show", methods={"GET"})
     */
    public function show(int $id): Response
    {
        $station = $this->getDoctrine()
            ->getRepository(Station::class)
            ->findOneById($id);

        $bikes = $this->getDoctrine()
            ->getRepository(Bike::class)
            ->findByStation($station);

        $data = array(
            'id' => $station->getId(),
            'name' => $station->getName(),
            'lon' => $station->getLon(),
            'lat' => $station->getLat(),
            'current_dockCount' => $station->getCurrentDockCount(),
            'bikes' => $bikes
        );

        return $this->json($data);
    }
}

templates/station/_delete_form.html.twig
<form method="post" action="{{ path('station_delete', {'id': station.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ station.id) }}">
    <button class="btn">Delete</button>
</form>

templates/station/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/station/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Station{% endblock %}

{% block body %}
    <h1>Edit Station</h1>

    {{ include('station/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('station_index') }}">back to list</a>

    {{ include('station/_delete_form.html.twig') }}
{% endblock %}

templates/station/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Station index{% endblock %}

{% block body %}
    <h1>Station index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Lon</th>
                <th>Lat</th>
                <th>Station_id</th>
                <th>Current_dockCount</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for station in stations %}
            <tr>
                <td>{{ station.id }}</td>
                <td>{{ station.name }}</td>
                <td>{{ station.lon }}</td>
                <td>{{ station.lat }}</td>
                <td>{{ station.stationId }}</td>
                <td>{{ station.currentDockCount }}</td>
                <td>
                    <a href="{{ path('station_show', {'id': station.id}) }}">show</a>
                    <a href="{{ path('station_edit', {'id': station.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('station_new') }}">Create new</a>
{% endblock %}

templates/station/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Station{% endblock %}

{% block body %}
    <h1>Create new Station</h1>

    {{ include('station/_form.html.twig') }}

    <a href="{{ path('station_index') }}">back to list</a>
{% endblock %}

templates/station/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Station{% endblock %}

{% block body %}
    <h1>Station</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ station.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ station.name }}</td>
            </tr>
            <tr>
                <th>Lon</th>
                <td>{{ station.lon }}</td>
            </tr>
            <tr>
                <th>Lat</th>
                <td>{{ station.lat }}</td>
            </tr>
            <tr>
                <th>Station_id</th>
                <td>{{ station.stationId }}</td>
            </tr>
            <tr>
                <th>Current_dockCount</th>
                <td>{{ station.currentDockCount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('station_index') }}">back to list</a>

    <a href="{{ path('station_edit', {'id': station.id}) }}">edit</a>

    {{ include('station/_delete_form.html.twig') }}
{% endblock %}